#                                                                                           #
#     __  ____       _ ______            __  ______                           __            #
#    /  |/  (_)___  (_) ____/___  ____  / /_/ ____/___  ____ _   _____  _____/ /____  _____ #
#   / /|_/ / / __ \/ / /_  / __ \/ __ \/ __/ /   / __ \/ __ \ | / / _ \/ ___/ __/ _ \/ ___/ #
#  / /  / / / / / / / __/ / /_/ / / / / /_/ /___/ /_/ / / / / |/ /  __/ /  / /_/  __/ /     #
# /_/  /_/_/_/ /_/_/_/    \____/_/ /_/\__/\____/\____/_/ /_/|___/\___/_/   \__/\___/_/      #
#                                                                                           #
#                           ᴅᴇᴠᴇʟᴏᴘᴇᴅ ʙʏ: GoldMember33                                      #
#               ᴘʀᴏᴊᴇᴄᴛ ʀᴇᴘᴏsɪᴛᴏʀʏ: https://github.com/GoldMember33/MiniFontConverter       #
#                                                                                           #

settings:
  #
  # Mensagens convertidas para MiniFont podem ser copiadas automaticamente
  # utilizando a opção [copiar] na component?
  # Isto vai fazer com que as mensagens sejam copiadas, sem a necessidade de
  # clicar e colar a mensagem na área de transferência, para depois copiar.
  #
  # Converted messages to MiniFont will be able to be copied automatically
  # using the [copy] option in the component?
  # This will make the messages copied without the need to click and paste
  # the message to the clipboard, to then copy.
  #
  set-copy-converted-message-contents-option: true
