messages:
  command-correct-usage: "<red>Uso correto: /minifont</red> <white><mensagem></white>"
  status-enabled: "<green>Ativado</green>"
  status-disabled: "<red>Desativado</red>"
  toggle-chat-feature-status: "<green>O status do recurso de chat foi alterado para:</green> <white>{status}</white>"
  click-to-copy-clipboard: "<blue>Clique para copiar a entrada</blue>"
  converted-message-output: "<green>Mensagem convertida para MiniFont: </green> "
  no-permission: "<red>Você não tem permissão para executar este comando!</red>"
  command-only-player: "<red>Este comando só pode ser usado por jogadores!</red>"
  toggle-chat-feature-command-correct-usage: "<red>Uso correto: /minifontchat</red> <white><true/false></white>"
  requires-valid-flag-for-chat-toggle-feature-usage: "<red>Uso correto: /minifontchat <toggle/true/false></red>"
  player-data-file-created: "<blue>Player data file created for:</blue> <white>{player}</white>"
  player-data-file-creation-failed: "<red>Failed to create player data file for:</red> <white>{player}</white>"
  player-data-file-creation-error: "<red>Error creating player data file for:</red> <white>{player}</white>: <dark_red>{error}</dark_red>"
  reloaded-configurations: "<green>Todas as configurações foram recarregadas!</green>"